import {
  Loader2,
  LogOut,
  Plus,
  CalendarIcon,
  CalendarClock,
  MoreHorizontal,
  Pencil,
  Trash2,
  Share,
  Square,
  CheckSquare2,
  MessageCircle,
  SendHorizontal,
  ChevronDown,
  ChevronUp,
  Check,
  Github,
  Link
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  logout: LogOut,
  plus: Plus,
  calendar: CalendarIcon,
  calendarClock: CalendarClock,
  more: MoreHorizontal,
  edit: Pencil,
  delete: Trash2,
  share: Share,
  square: Square,
  checkedSquare: CheckSquare2,
  comments: MessageCircle,
  send: SendHorizontal,
  arrowDown: ChevronDown,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  check: Check,
  github: Github,
  link: Link
};
